config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'
  resources :connections, only: [:new]
  # resources :characters
  namespace :api do
    namespace :v1 do
      resources :connections, only: [:index], defaults: {format: :json}
    end
  end

end

app/models/character.rb
class Character
  include Neo4j::ActiveNode
  property :character_id
  property :name
  property :deck
  property :image

  validates :character_id, :presence => true, :uniqueness => true
  validates :name,         :presence => true, :uniqueness => true

  has_many :both, :friends, type: :friends, model_class: :Character, unique: true
  has_many :both, :enemies, type: :enemies, model_class: :Character, unique: true

  scope :in_order, ->(identifier){ order("n.#{identifier} ASC")}

  def self.find_connection(char1, char2)
    first_character     = Character.find_by(name: char1)
    second_character    = Character.find_by(name: char2)
    Neo4j::Session.query("MATCH p=
                        (d:Character {name: '#{first_character.name}'})
                        -[*1..5]-
                        (m:Character {name: '#{second_character.name}'})
                         RETURN p
                         LIMIT 50").to_a
  end

end

app/models/connection.rb
class Connection

  def self.service
    Neo4jService.new
  end

  def self.get_nodes(connection)
    connection.first["p"]["nodes"].map do |node|
      node.gsub!("#{ENV['db']}", "")
      id = node.gsub('node/', '')
      {id: id, label: service.neo4j_node(node) }
    end
  end

  def self.get_edges(connection)
    connection.first["p"]["relationships"].map do |relationship|
      relationship.gsub!("#{ENV['db']}", "")
      rel = service.neo4j_edge(relationship)
      source_id = rel[0].gsub("#{ENV['db']}", "")
      source_id.gsub!("node/", "")
      target_id = rel[1].gsub("#{ENV['db']}", "")
      target_id.gsub!("node/", "")
      {from: source_id, to: target_id }
      # {source: source_id, target: target_id, label: rel[2]}
    end
  end


private

  def self.build_object(data)
    OpenStruct.new(data)
  end

end

app/controllers/api/v1/connections_controller.rb
class Api::V1::ConnectionsController < ApplicationController

  def index
    @connections = Character.find_connection(params[:first_character], params[:second_character])
    render  json: @connections.as_json, serializer: ::ConnectionSerializer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/connections/_form.html.erb
<%= form_tag(api_v1_connections_path, method: "get") do %>
  <%= label_tag(:first_character, "Choose first character:") %>
  <%= collection_select(:first_character, :character_id, Character.all.in_order(:name), :character_id, :name) %>
  <%= label_tag(:second_character, "Choose second character:") %>
  <%= collection_select(:second_character, :character_id, Character.all.in_order(:name), :character_id, :name) %>
  <button id="find-connection">submit</button>
<% end %>

app/views/connections/new.html.erb
<%= render partial: 'shared/search_nav' %>
<div class="superheroes">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-body graph hide">
            Click a character on the right to learn more
            <div id="learn-more"></div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="panel panel-default graph hide">
          <div class="panel-body">
            <div id="cy"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComicDb</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img alt="6 Degrees" src="<%= image_path 'logo.png' %>">
      </a>
    </div>
  </div>
</nav>

app/views/shared/_search_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img alt="6 Degrees" src="<%= image_path 'logo.png' %>">
      </a>
    </div>
    <ul class="nav navbar-nav navbar-right search">
      <li class="directions">How are your favorite comic book characters connected?</li>
      <li><%= render partial: 'connections/form', class: "navbar-form navbar-left" %></li>
    </ul>
  </div>
</nav>

app/views/welcome/index.html.erb
<%= render partial: 'shared/nav' %>
<div class="superheroes">
  <div class="container">
    <div class="jumbotron">
      <h1>6 Degrees</h1>
      <p>How are comic book characters connected?</p>
      <p>You might be surprised?</p>
      <p><%= button_to "Get Started", new_connection_path,
                                      method: :get,
                                      class: "btn btn-danger btn-lg" %></p>
    </div>
  </div>
</div>